name: Angel Aguayo
favicon: null
layout_spectrum: 0.78017
typography_spectrum: 0.8853
title: Diseños WEB y Diseño Grafico Angel Aguayo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f3f3f'
    - '#697334'
    - '#afbf5d'
    - '#fefefe'
    - '#080a09'
  brandStrength: 0.9375
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
