name: Angel Aguayo
favicon: null
layout_spectrum: 0.42628170014359057
typography_spectrum: 0.6899588753003627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f3f3f'
    - '#697334'
    - '#afbf5d'
    - '#fefefe'
    - '#080a09'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
