name: Angel Aguayo
favicon: null
layout_spectrum: 0.42628170014359057
typography_spectrum: 0.6899588753003627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03594164736568928
  lightness: 0.08792298729531467
  saturation: 0.2280982614029199
  rhythmicContrast: 0.4576627337373793
purpose: []
